### ISSUE TITLE
v0.3.0 To-do List

### ISSUE THREAD

**Issue by xrq-phys** [xrq-phys/BLIS.jl#7]
- [x] Waiting for more Arm64 works in the upstream (by myself, though).
- [ ] Introduce more tests (sizes, transpose, etc.)
- [ ] **Unsure** Option to not override the `LinearAlgebra` module.
- [ ] [Mixed precision](https://github.com/JuliaLinearAlgebra/BLIS.jl/issues/7#issuecomment-1046077289)

**Comment by xrq-phys** [comment]
Just noticed that since `0.1.0`, `gemmt` is introduced while upstream has `≥0.8.0` as requirement.
Hence I should tag the current `HEAD` as `0.2.0` and make this roadmap `0.3.0`.

**Comment by xrq-phys** [comment]
And another thing:

- [ ] Overriding `gemm!` alone seems forwarding generic strides but not mixed precision. I'd be good to also override somehow `mul!{A::Array{TA},B::Array{TB},C::Array{TC}}{TA≠TB≠TC}` for mixed precision support.

cf. log:
```
# Generic striding is good:
julia> @benchmark view(A, 1:2:1000, :)*B setup=(A=rand(Float64, 1000, 1000); B=rand(Float64, 1000, 1000))
BenchmarkTools.Trial: 22 samples with 1 evaluation.
 Range (min … max):  228.803 ms … 233.134 ms  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     229.311 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   229.954 ms ±   1.277 ms  ┊ GC (mean ± σ):  0.00% ± 0.00%

julia> using BLIS; @benchmark view(A, 1:2:1000, :)*B setup=(A=rand(Float64, 1000, 1000); B=rand(Float64, 1000, 1000))
BenchmarkTools.Trial: 213 samples with 1 evaluation.
 Range (min … max):  20.919 ms …  21.676 ms  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     21.161 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   21.137 ms ± 109.760 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%
```
```
# Mixed precision not reaching BLIS directly:
julia> A=rand(Float64, 1000, 1000); B=rand(Float32, 1000, 1000);
julia> using Cthulhu; @descend A*B
...
   %7  = invoke copyto_axcheck!(::Matrix{Float64},::Matrix{Float32})::Matrix{Float64}
   %8  = invoke gemm!(::Char,::Char,::Float64,::Matrix{Float64},::Matrix{Float64},::Float64,::Matrix{Float64})::Matrix{Float64}
 • ↩
```
